name: Build and Upload Go Client for Windows

on:
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Install Go packages
        run: go mod tidy && go mod download

      - name: Build Binary
        shell: powershell
        run: |
          $env:GOOS="windows"
          $env:GOARCH="amd64"
          $env:ADDR="${{ vars.ADDR }}"
          go build -ldflags "-X github.com/kainn9/grpc_game/client_util.BuildTime=true" -o bin/application.exe ./client
          Copy-Item -Path ".\client\sprites" -Destination ".\bin\sprites" -Recurse
          Copy-Item -Path ".\client\backgrounds" -Destination ".\bin\backgrounds" -Recurse
          Copy-Item -Path ".\client\audio" -Destination ".\bin\audio" -Recurse
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Application
          path: bin
